import type { Metadata } from "next"
import "@/styles/globals.css"
import { ThemeProvider } from "next-themes"
import { Toaster } from "@/components/ui/toaster"
import { Header } from "@/components/header"
import { ThemeSwitcher } from "@/components/theme-switcher"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ThemeProvider attribute="class">
      <Toaster />
      <div className="mx-auto w-full max-w-2xl">
        <Header />
        {children}
        <div className="fixed bottom-4 right-4 md:hidden">
          <ThemeSwitcher />
        </div>
      </div>
    </ThemeProvider>
  )
}
