import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Title from '@/components/Title'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dan&apos;s Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-screen'>
        <Navbar />
        <div className='w-full flex justify-center'>
          <Title />
        </div>
      </div>
    </>
  )
}
