import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Intro from '@/components/Intro'
import About from '@/components/About'
import Works from '@/components/Works'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dan&apos;s Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen flex flex-col items-center overflow-auto">
        <Navbar />
        <Intro />
        <About />
        <Works />
      </div>
    </>
  )
}
